### ISSUE TITLE
ValueError: Negative values in data passed to NMF

### ISSUE THREAD

**Issue by Dominic7227** [CostaLab/scopen#16]
Hi, I tried the command `scopen` on my count data (all integers and non-negative), but it threw an error that there exist negative values for NMF input. Then I checked the TF-IDF function you used in the source code, and it showed that the TF-IDF transformation would produce negative values. 
![image](https://user-images.githubusercontent.com/34212762/142085726-71c4cf02-2b7a-4528-b17e-c0900dc63ad3.png)

**Comment by lzj1769** [comment]
Hi @Dominic7227 

Can you provide me with the count data? So I can figure it out.
You can replace all the cell and peak names with a random name if you want.

Thanks

**Comment by fl-yu** [comment]
encounter the same issue..

**Comment by SidG13** [comment]
Hi @lzj1769 , I'm encountering the same issue as previous commenters. I installed scopen v1.0.1 (the newest version) from pip. I'm running this on python3.8. I've already checked that my entire input matrix is non-negative. Could you please let me know what you did to fix this?

**Comment by Dududu233** [comment]
encounter the same issue..

**Comment by Dududu233** [comment]
The problem is solved. You should make sure that your matrix does not contain reads larger than 128, otherwise this statement in utils.py will not work properly.
![image](https://github.com/CostaLab/scopen/assets/86656612/65cfd023-3e85-4537-ac20-bc1440295abf)
