### ISSUE TITLE
Can I run scopen with  TF-IDF  matrix?

### ISSUE THREAD

**Issue by bitcometz** [CostaLab/scopen#18]
Hello,
Thanks for this great software.

Could I run scOpen with TF-IDF as inputs. For more specific, 
my ATAC-seq peak counts  have been transformed with [TF-IDF](https://muon.readthedocs.io/en/latest/api/generated/muon.atac.pp.tfidf.html?highlight=tfidf) using the default log(TF) * log(IDF) output (chromatin accessibility) and stored as `h5` format.

Thanks !!!

**Comment by lzj1769** [comment]
Hi,

The command line of scOpen does not support running it on transformed matrix, unfortunately.

However, you can use the NMF function provided by scopen to perform dimensionality reduction. 
In this case, you might need to implement a few functions to access the data in h5 format and call the function in sOpen.

Best,
Zhijian
